import { useState, useEffect, useRef } from 'react';
import { getAuth } from 'firebase/auth';
import { useChatHistory, useEventMedia, eventKeys } from './useEvents';
import { ASSET_TYPES, type WsAgentMessage } from '../types/chat';
import { useQueryClient } from '@tanstack/react-query';

export function useEventSession(eventId: string) {
  const [messages, setMessages] = useState<any[]>([]);
  const [contentCards, setContentCards] = useState<any[]>([]);
  const [isChatConnected, setIsChatConnected] = useState(false);
  const [isAgentThinking, setIsAgentThinking] = useState(false);
  const [sessionInfo, setSessionInfo] = useState<{ userId: string; sessionId: string } | null>(null);
  const [isFetchingSession, setIsFetchingSession] = useState(false);
  const queryClient = useQueryClient();
  
  const wsRef = useRef<WebSocket | null>(null);

  // 1. Determine Session ID by fetching from the backend
  useEffect(() => {
    const auth = getAuth();
    let cancelled = false;

    const unsubscribe = auth.onAuthStateChanged(async (user) => {
      if (!user || !eventId) {
        setSessionInfo(null);
        return;
      }

      try {
        setIsFetchingSession(true);
        // Fetch the session ID from the backend (generated by the ADK session service)
        const token = await user.getIdToken();
        const res = await fetch(
          `${import.meta.env.VITE_API_URL}/events/${eventId}/session`,
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (!res.ok) {
          console.error('Failed to fetch session info:', res.status);
          return;
        }
        const data = await res.json();
        if (!cancelled) {
          setSessionInfo({ userId: user.uid, sessionId: data.session_id });
        }
      } catch (err) {
        console.error('Error fetching session info:', err);
      } finally {
        if (!cancelled) {
          setIsFetchingSession(false);
        }
      }
    });

    return () => {
      cancelled = true;
      unsubscribe();
    };
  }, [eventId]);

  // 2. Fetch Initial History & Media
  const { data: historyData, isLoading: isLoadingHistory } = useChatHistory(sessionInfo?.sessionId || '');
  const { data: mediaData, isLoading: isLoadingMedia } = useEventMedia(eventId, sessionInfo?.sessionId || '');

  useEffect(() => {
    if (historyData?.messages) {
      // Input is usually chronological from backend, so we append
      // If backend history is reversed, we'd .reverse() it here
      const historyMsgs = historyData.messages.map((m: any) => ({
        role: m.role,
        text: m.text,
        mediaRefs: m.media_refs || [],
        timestamp: new Date(m.timestamp ? m.timestamp : Date.now()).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      }));
      setMessages(historyMsgs);
    }
  }, [historyData]);

  useEffect(() => {
    if (mediaData?.media_assets) {
      // Sort content cards chronologically (ascending)
      const sortedMedia = [...mediaData.media_assets].sort(
        (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()
      );
      setContentCards(sortedMedia);
    }
  }, [mediaData]);

  // 3. WebSocket Connection
  useEffect(() => {
    if (!sessionInfo || !eventId) return;

    let ws: WebSocket;
    let reconnectTimeout: ReturnType<typeof setTimeout>;
    let reconnectAttempts = 0;
    const maxReconnectDelay = 30000;
    let isActive = true;

    const connectWs = async () => {
      try {
        const auth = getAuth();
        const token = await auth.currentUser?.getIdToken();
        if (!token || !isActive) return;

        const wsUrl = `${import.meta.env.VITE_API_URL?.replace('http', 'ws')}/chat/ws/${eventId}/${sessionInfo.userId}/${sessionInfo.sessionId}?token=${token}`;
        ws = new WebSocket(wsUrl);
        wsRef.current = ws;

        ws.onopen = () => {
          setIsChatConnected(true);
          reconnectAttempts = 0;
        };

        ws.onmessage = (event) => {
          try {
            const data = JSON.parse(event.data) as WsAgentMessage;
            
            // "thinking" is sent immediately when the agent starts processing,
            // before potentially long image generation completes.
            if (data.type === 'error') {
              setIsAgentThinking(false);
              // Handle as alert for immediate user feedback
              alert(data.text || "Oops! I encountered an error. Please try again.");
              return;
            }

            if (data.type === 'state_update') {
              // Trigger a refetch of the event details (e.g. name, type)
              queryClient.invalidateQueries({ queryKey: eventKeys.detail(eventId) });
              return;
            }
            
            if (data.type === 'message') {
              // Clear the thinking indicator when a real response arrives
              setIsAgentThinking(false);
              
              const newMsg = {
                role: 'assistant' as const,
                text: data.text,
                mediaRefs: data.media_refs || [],
                timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
              };
              
              setMessages(prev => [...prev, newMsg]); // Append

              if (data.media_refs && data.media_refs.length > 0) {
                const newCards = data.media_refs.map(ref => ({
                  id: ref.asset_id,
                  title: `Generated ${ref.asset_type === ASSET_TYPES.IMAGE ? 'Image' : 'Video'}`,
                  asset_type: ref.asset_type,
                  content_category: ref.asset_type === ASSET_TYPES.VIDEO ? 'video' : 'poster',
                  public_url: ref.url,
                  thumbnail_url: ref.thumbnail_url,
                  created_at: new Date().toISOString()
                }));
                
                setContentCards(prev => {
                  const existingIds = prev.map(p => p.id);
                  const uniqueNew = newCards.filter(c => !existingIds.includes(c.id));
                  return [...prev, ...uniqueNew]; // Append
                });
              }
            }
          } catch (e) {
            console.error("Failed to parse WS msg", event.data);
          }
        };

        ws.onclose = () => {
          setIsChatConnected(false);
          const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), maxReconnectDelay);
          reconnectAttempts++;
          reconnectTimeout = setTimeout(connectWs, delay);
        };
      } catch (err) {
        console.error("WS connect failed", err);
        const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), maxReconnectDelay);
        reconnectAttempts++;
        reconnectTimeout = setTimeout(connectWs, delay);
      }
    };

    connectWs();

    return () => {
      isActive = false;
      clearTimeout(reconnectTimeout);
      if (ws) {
        ws.onmessage = null;
        ws.onclose = null;
        ws.close();
      }
      // Reset state on event change/unmount
      setMessages([]);
      setContentCards([]);
    };
  }, [sessionInfo, eventId]);

  const handleSendMessage = async (text: string, files?: File[]) => {
    if ((!text.trim() && (!files || files.length === 0)) || !wsRef.current || wsRef.current.readyState !== WebSocket.OPEN) return;
    
    // Build local preview media refs for immediate display in the user bubble
    const localPreviews: any[] = (files || [])
      .filter(f => f.type.startsWith('image/'))
      .map(f => ({
        asset_id: `local-${Math.random().toString(36).slice(2, 9)}`,
        url: URL.createObjectURL(f),
        thumbnail_url: URL.createObjectURL(f),
        mime_type: f.type,
        asset_type: ASSET_TYPES.IMAGE,
      }));

    const userMsg = {
      role: 'user' as const,
      text: text,
      mediaRefs: localPreviews.length > 0 ? localPreviews : undefined,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    setMessages(prev => [...prev, userMsg]);
    setIsAgentThinking(true);

    // Upload files to GCS and collect the resulting gs:// URIs
    const imageUrls: string[] = [];
    if (files && files.length > 0 && sessionInfo) {
      const auth = getAuth();
      const token = await auth.currentUser?.getIdToken();
      if (!token) {
        console.error('No auth token for file upload');
        return;
      }
      const apiUrl = import.meta.env.VITE_API_URL;
      const bucketName = import.meta.env.VITE_FIREBASE_STORAGE_BUCKET;

      for (const file of files) {
        try {
          // 1. Get signed URL from backend
          const params = new URLSearchParams({
            event_id: eventId,
            session_id: sessionInfo.sessionId,
            object_name: file.name,
            content_type: file.type,
          });
          const signedRes = await fetch(`${apiUrl}/media/signed-url?${params}`, {
            headers: { Authorization: `Bearer ${token}` },
          });
          if (!signedRes.ok) {
            console.error('Failed to get signed URL:', signedRes.status);
            continue;
          }
          const { signed_url, dest_path } = await signedRes.json();

          // 2. Upload the file to GCS (or local endpoint)
          await fetch(signed_url, {
            method: 'PUT',
            headers: { 'Content-Type': file.type },
            body: file,
          });

          // 3. Build the final GCS URI
          const gsUri = bucketName
            ? `gs://${bucketName}/${dest_path}`
            : `local://${dest_path}`;
          imageUrls.push(gsUri);

          // 4. Record the media asset in Firestore via POST /events/{eventId}/media
          await fetch(`${apiUrl}/events/${eventId}/media`, {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${token}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              session_id: sessionInfo.sessionId,
              gcs_path: gsUri,
              asset_type: file.type.startsWith('image/') ? ASSET_TYPES.IMAGE : ASSET_TYPES.DOCUMENT,
              mime_type: file.type,
              title: file.name,
            }),
          });
        } catch (err) {
          console.error(`Failed to upload ${file.name}:`, err);
        }
      }
    }

    // Send the message (with optional image URIs) over WebSocket
    const wsPayload: Record<string, any> = { text };
    if (imageUrls.length > 0) {
      wsPayload.image_urls = imageUrls;
    }
    wsRef.current.send(JSON.stringify(wsPayload));
  };

  return {
    messages,
    contentCards,
    isChatConnected,
    isAgentThinking,
    handleSendMessage,
    sessionInfo,
    setMessages,
    setContentCards,
    isLoading: isFetchingSession || isLoadingHistory || isLoadingMedia
  };
}
