import { useState, useEffect, useRef } from 'react';
import { getAuth } from 'firebase/auth';
import { useChatHistory, useEventMedia, eventKeys } from './useEvents';
import type { WsAgentMessage } from '../types/chat';
import { useQueryClient } from '@tanstack/react-query';

export function useEventSession(eventId: string) {
  const [messages, setMessages] = useState<any[]>([]);
  const [contentCards, setContentCards] = useState<any[]>([]);
  const [isChatConnected, setIsChatConnected] = useState(false);
  const [isAgentThinking, setIsAgentThinking] = useState(false);
  const [sessionInfo, setSessionInfo] = useState<{ userId: string; sessionId: string } | null>(null);
  const queryClient = useQueryClient();
  
  const wsRef = useRef<WebSocket | null>(null);

  // 1. Determine Session ID by fetching from the backend
  useEffect(() => {
    const auth = getAuth();
    let cancelled = false;

    const unsubscribe = auth.onAuthStateChanged(async (user) => {
      if (!user || !eventId) {
        setSessionInfo(null);
        return;
      }

      try {
        // Fetch the session ID from the backend (generated by the ADK session service)
        const token = await user.getIdToken();
        const res = await fetch(
          `${import.meta.env.VITE_API_URL}/events/${eventId}/session`,
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (!res.ok) {
          console.error('Failed to fetch session info:', res.status);
          return;
        }
        const data = await res.json();
        if (!cancelled) {
          setSessionInfo({ userId: user.uid, sessionId: data.session_id });
        }
      } catch (err) {
        console.error('Error fetching session info:', err);
      }
    });

    return () => {
      cancelled = true;
      unsubscribe();
    };
  }, [eventId]);

  // 2. Fetch Initial History & Media
  const { data: historyData } = useChatHistory(sessionInfo?.sessionId || '');
  const { data: mediaData } = useEventMedia(eventId, sessionInfo?.sessionId || '');

  useEffect(() => {
    if (historyData?.messages) {
      // Input is usually chronological from backend, so we append
      // If backend history is reversed, we'd .reverse() it here
      const historyMsgs = historyData.messages.map((m: any) => ({
        role: m.role,
        text: m.text,
        mediaRefs: m.media_refs || [],
        timestamp: new Date(m.timestamp ? m.timestamp : Date.now()).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      }));
      setMessages(historyMsgs);
    }
  }, [historyData]);

  useEffect(() => {
    if (mediaData?.media_assets) {
      // Sort content cards chronologically (ascending)
      const sortedMedia = [...mediaData.media_assets].sort(
        (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()
      );
      setContentCards(sortedMedia);
    }
  }, [mediaData]);

  // 3. WebSocket Connection
  useEffect(() => {
    if (!sessionInfo || !eventId) return;

    let ws: WebSocket;
    let reconnectTimeout: ReturnType<typeof setTimeout>;
    let reconnectAttempts = 0;
    const maxReconnectDelay = 30000;
    let isActive = true;

    const connectWs = async () => {
      try {
        const auth = getAuth();
        const token = await auth.currentUser?.getIdToken();
        if (!token || !isActive) return;

        const wsUrl = `${import.meta.env.VITE_API_URL?.replace('http', 'ws')}/chat/ws/${eventId}/${sessionInfo.userId}/${sessionInfo.sessionId}?token=${token}`;
        ws = new WebSocket(wsUrl);
        wsRef.current = ws;

        ws.onopen = () => {
          setIsChatConnected(true);
          reconnectAttempts = 0;
        };

        ws.onmessage = (event) => {
          try {
            const data = JSON.parse(event.data) as WsAgentMessage;
            
            // "thinking" is sent immediately when the agent starts processing,
            // before potentially long image generation completes.
            if (data.type === 'error') {
              setIsAgentThinking(false);
              // Handle as alert for immediate user feedback
              alert(data.text || "Oops! I encountered an error. Please try again.");
              return;
            }

            if (data.type === 'state_update') {
              // Trigger a refetch of the event details (e.g. name, type)
              queryClient.invalidateQueries({ queryKey: eventKeys.detail(eventId) });
              return;
            }
            
            if (data.type === 'message') {
              // Clear the thinking indicator when a real response arrives
              setIsAgentThinking(false);
              
              const newMsg = {
                role: 'assistant' as const,
                text: data.text,
                mediaRefs: data.media_refs || [],
                timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
              };
              
              setMessages(prev => [...prev, newMsg]); // Append

              if (data.media_refs && data.media_refs.length > 0) {
                const newCards = data.media_refs.map(ref => ({
                  id: ref.asset_id,
                  title: `Generated ${ref.asset_type === 'image' ? 'Image' : 'Video'}`,
                  asset_type: ref.asset_type,
                  content_category: ref.asset_type === 'video' ? 'video' : 'poster',
                  public_url: ref.url,
                  thumbnail_url: ref.thumbnail_url,
                  created_at: new Date().toISOString()
                }));
                
                setContentCards(prev => {
                  const existingIds = prev.map(p => p.id);
                  const uniqueNew = newCards.filter(c => !existingIds.includes(c.id));
                  return [...prev, ...uniqueNew]; // Append
                });
              }
            }
          } catch (e) {
            console.error("Failed to parse WS msg", event.data);
          }
        };

        ws.onclose = () => {
          setIsChatConnected(false);
          const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), maxReconnectDelay);
          reconnectAttempts++;
          reconnectTimeout = setTimeout(connectWs, delay);
        };
      } catch (err) {
        console.error("WS connect failed", err);
        const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), maxReconnectDelay);
        reconnectAttempts++;
        reconnectTimeout = setTimeout(connectWs, delay);
      }
    };

    connectWs();

    return () => {
      isActive = false;
      clearTimeout(reconnectTimeout);
      if (ws) {
        ws.onmessage = null;
        ws.onclose = null;
        ws.close();
      }
      // Reset state on event change/unmount
      setMessages([]);
      setContentCards([]);
    };
  }, [sessionInfo, eventId]);

  const handleSendMessage = (text: string) => {
    if (!text.trim() || !wsRef.current || wsRef.current.readyState !== WebSocket.OPEN) return;
    
    const userMsg = {
      role: 'user' as const,
      text: text,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    setMessages(prev => [...prev, userMsg]); // Append
    // Set thinking immediately to give instant feedback before server confirms
    setIsAgentThinking(true);
    
    wsRef.current.send(JSON.stringify({ text }));
  };

  return {
    messages,
    contentCards,
    isChatConnected,
    isAgentThinking,
    handleSendMessage,
    sessionInfo,
    setMessages,
    setContentCards
  };
}
