"""Firestore service for session and event persistence."""
import asyncio
from datetime import datetime
from typing import Optional, Dict, Any, List

from google.cloud import firestore
from google.cloud.firestore_v1.base_query import FieldFilter, And

from ..config import settings

import logging

# Initialize client lazily to prevent DefaultCredentialsError on import
_db = None
logger = logging.getLogger(__name__)


def get_db() -> firestore.AsyncClient:
    global _db
    if _db is None:
        _db = firestore.AsyncClient(project=settings.firebase_project_id)
    return _db


def _normalize_timestamps(data: Dict[str, Any]) -> Dict[str, Any]:
    """Convert Firestore Timestamp objects to native datetimes for known fields."""
    for field in ("created_at", "updated_at", "start_time", "end_time"):
        value = data.get(field)
        # Firestore Timestamp has a to_datetime() method; guard via duck typing
        if value is not None and hasattr(value, "to_datetime"):
            data[field] = value.to_datetime()
    return data


def generate_document_id(collection: str = "events") -> str:
    """Generate a unique Firestore document ID without creating the document.

    This is useful when you need the ID upfront (e.g. to seed into ADK session
    state) before the document is actually written.
    """
    return get_db().collection(collection).document().id


async def create_event_and_session(
    user_id: str,
    event_data: Optional[Dict[str, Any]] = None,
    session_id: Optional[str] = None,
    event_id: Optional[str] = None,
) -> Dict[str, str]:
    """
    Creates a draft event and a new chat session in a single batch write.

    Args:
        user_id: The authenticated user's ID.
        event_data: Optional fields to merge into the event document.
        session_id: The session ID (generated by the session service).
            If None, Firestore will auto-generate one.
        event_id: The event ID to use. If None, Firestore will auto-generate one.

    Returns:
        A dict with 'event_id' and 'session_id'.
    """
    try:
        db = get_db()
        batch = db.batch()

        # Build the base event document
        event_doc: Dict[str, Any] = {
            "created_by": user_id,
            "updated_by": user_id,
            "status": "draft",
            "created_at": firestore.SERVER_TIMESTAMP,
            "updated_at": firestore.SERVER_TIMESTAMP,
        }

        # Merge any caller-supplied fields (name, description, metadata, …)
        if event_data:
            event_doc.update(event_data)

        # Use the provided event_id if given, otherwise auto-generate
        if event_id:
            event_ref = db.collection("events").document(event_id)
        else:
            event_ref = db.collection("events").document()
            event_id = event_ref.id

        batch.set(event_ref, event_doc)

        # Use the externally-provided session_id if given,
        # otherwise let Firestore auto-generate one.
        if session_id:
            session_ref = db.collection("chat_sessions").document(session_id)
        else:
            session_ref = db.collection("chat_sessions").document()
            session_id = session_ref.id

        batch.set(
            session_ref,
            {
                "session_id": session_id,
                "user_id": user_id,
                "event_id": event_ref.id,
                "status": "active",
                "created_at": firestore.SERVER_TIMESTAMP,
                "metadata": {},
            },
        )

        await batch.commit()
        return {"event_id": event_ref.id, "session_id": session_id}
    except Exception as e:
        logger.error(f"Error creating event and session for user {user_id}: {e}")
        raise


async def update_event(event_id: str, event_data: Dict[str, Any]) -> None:
    """Updates an existing event's info in the top-level collection."""
    try:
        doc_ref = get_db().collection("events").document(event_id)
        data = dict(event_data)
        data["updated_at"] = firestore.SERVER_TIMESTAMP
        await doc_ref.set(data, merge=True)
    except Exception as e:
        logger.error(f"Error updating event {event_id}: {e}")
        raise


async def get_events_for_user(user_id: str, offset: int, limit: int) -> List[Dict[str, Any]]:
    """
    Returns a page of events for a given user, ordered by updated_at descending.
    """
    try:
        db = get_db()
        query = (
            db.collection("events")
            .where(filter=FieldFilter("created_by", "==", user_id))
            .order_by("updated_at", direction=firestore.Query.DESCENDING)
        )

        # Apply offset/limit; for small datasets this is fine for now.
        query = query.offset(offset).limit(limit)

        results: List[Dict[str, Any]] = []
        async for doc in query.stream():
            data = doc.to_dict() or {}
            # pyre-ignore[16]
            data["id"] = doc.id
            results.append(_normalize_timestamps(data))
        return results
    except Exception as e:
        logger.error(f"Error fetching events for user {user_id}: {e}")
        raise


async def count_events_for_user(user_id: str) -> int:
    """
    Counts total number of events for a given user.
    """
    try:
        db = get_db()
        query = db.collection("events").where(filter=FieldFilter("created_by", "==", user_id))
        count = 0
        async for _ in query.stream():
            count += 1
        return count
    except Exception as e:
        logger.error(f"Error counting events for user {user_id}: {e}")
        raise


async def get_session_by_event_id(event_id: str) -> Optional[Dict[str, Any]]:
    """Fetches the chat_sessions record associated with the given event_id."""
    try:
        db = get_db()
        query = db.collection("chat_sessions").where(
            filter=FieldFilter("event_id", "==", event_id)
        ).limit(1)
        async for doc in query.stream():
            data = doc.to_dict() or {}
            # pyre-ignore[16]
            data["id"] = doc.id
            return data
        return None
    except Exception as e:
        logger.error(f"Error fetching session for event {event_id}: {e}")
        raise


async def update_session_id_for_event(event_id: str, new_session_id: str) -> bool:
    """Updates the session_id for a given event_id in Firestore."""
    try:
        db = get_db()
        query = db.collection("chat_sessions").where(
            filter=FieldFilter("event_id", "==", event_id)
        ).limit(1)
        
        async for doc in query.stream():
            await doc.reference.update({"session_id": new_session_id})
            return True
        return False
    except Exception as e:
        logger.error(f"Error updating session_id for event {event_id}: {e}")
        raise


async def get_event_by_id(event_id: str) -> Optional[Dict[str, Any]]:
    """
    Fetches a single event document by id, or None if it does not exist.
    """
    try:
        db = get_db()
        doc_ref = db.collection("events").document(event_id)
        snapshot = await doc_ref.get()
        if not snapshot.exists:
            return None
        data = snapshot.to_dict() or {}
        # pyre-ignore[16]
        data["id"] = snapshot.id
        return _normalize_timestamps(data)
    except Exception as e:
        logger.error(f"Error fetching event {event_id}: {e}")
        raise


# ── Media Assets ──────────────────────────────────────────────────────────────

def gs_to_public_url(gs_uri: str) -> str:
    """Convert a gs://bucket/path URI to a public HTTPS URL.

    For local dev URIs (local://...) returns a local serving path.
    """
    if gs_uri.startswith("local://"):
        return f"/media/local/{gs_uri.replace('local://', '')}"
    if gs_uri.startswith("gs://"):
        # gs://bucket-name/path → https://storage.googleapis.com/bucket-name/path
        return gs_uri.replace("gs://", "https://storage.googleapis.com/", 1)
    return gs_uri


async def save_media_asset(asset_data: Dict[str, Any]) -> str:
    """Save a media asset record to the media_assets collection.

    Args:
        asset_data: Dict matching the media_assets schema
            (event_id, session_id, source, asset_type, gcs_path, etc.)

    Returns:
        The auto-generated Firestore document ID (= shared asset_id).
    """
    try:
        db = get_db()
        doc_ref = db.collection("media_assets").document()
        asset_data["created_at"] = firestore.SERVER_TIMESTAMP
        # Ensure public_url is derived from gcs_path if not explicitly set
        if "public_url" not in asset_data and "gcs_path" in asset_data:
            asset_data["public_url"] = gs_to_public_url(asset_data["gcs_path"])
        await doc_ref.set(asset_data)
        logger.info(f"Saved media asset {doc_ref.id} for event {asset_data.get('event_id')}")
        return doc_ref.id
    except Exception as e:
        logger.error(f"Error saving media asset: {e}")
        raise


async def get_media_for_event(
    event_id: str,
    session_id: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Fetch media assets for an event, optionally filtered by session_id.

    Args:
        event_id: The event to query assets for.
        session_id: Optional; narrows results to a specific chat session.

    Returns:
        List of asset dicts, each with an 'id' field (the Firestore doc ID).
    """
    try:
        db = get_db()
        # Querying by event_id primarily. Ignoring session_id for now to ensure reliability
        # across agent session restarts/refreshes.
        query = db.collection("media_assets").where(filter=FieldFilter("event_id", "==", event_id))

        results: List[Dict[str, Any]] = []
        async for doc in query.stream():
            data = doc.to_dict() or {}
            # pyre-ignore[16]
            data["id"] = doc.id
            results.append(_normalize_timestamps(data))

        # Sort in memory to avoid needing composite indexes in Firestore
        results.sort(
            key=lambda x: x.get("created_at") or datetime.min, 
            reverse=True
        )
        return results
    except Exception as e:
        logger.error(f"Error fetching media for event {event_id}: {e}")
        raise

