# Video Generation
VIDEO_DURATION_SECONDS = 5
VEO_POLL_INTERVAL_SECONDS = 5
VIDEO_ASPECT_RATIO = "16:9"
VIDEO_RESOLUTION = "1080p"

# Image Processing
IMAGE_MAX_WIDTH = 1024
IMAGE_JPEG_QUALITY = 85

# Media
SIGNED_URL_EXPIRATION_MINUTES = 15
