"""MultimodalContentCreator — generates interleaved text + images for event content.

Uses a Gemini image-generation model with response_modalities=["TEXT", "IMAGE"]
to produce native inline images alongside prose. The after_model_callback
intercepts the raw multimodal response, uploads images to GCS, saves asset
records in Firestore, and constructs a structured JSON response that chat.py
can parse into media_refs for the frontend.
"""

import json
import uuid
import asyncio
import logging
import traceback
from typing import Optional

from google.adk.agents import LlmAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.models import LlmResponse
from google.genai import types as genai_types
from app.services.firestore_service import save_media_asset, gs_to_public_url
from app.utils.helpers import resize_and_upload_image
from app.utils.constants import THUMBNAIL_MAX_WIDTH

logger = logging.getLogger(__name__)

# Maximum images to upload per agent call — prevents spamming the API and
# hitting per-minute quota limits during hackathon / free-tier usage.
MAX_IMAGES_PER_CALL = 3


async def process_generated_images_callback(
    callback_context: CallbackContext, llm_response: LlmResponse
) -> Optional[LlmResponse]:
    """Intercepts the model's native multimodal response (text + inline_data images),
    uploads images to GCS, saves Firestore media_asset records, and returns a single
    structured JSON text part so downstream agents (ContentGenerator → chat.py) can
    extract media_refs for the frontend.

    Returns None (passthrough) if the response contains no images.
    """
    if not llm_response.content or not llm_response.content.parts:
        return None

    # --- 1. Separate text parts from binary image parts ---
    text_chunks: list[str] = []
    binary_images: list[bytes] = []

    for part in llm_response.content.parts:
        if part.text:
            text_chunks.append(part.text)
        elif part.inline_data and part.inline_data.data:
            binary_images.append(part.inline_data.data)

    # If the model didn't generate any images, pass through unchanged
    if not binary_images:
        logger.warning(
            f"process_generated_images_callback: no images in response. "
            f"Raw text generated by model: {repr(text_chunks)[:1000]}"
        )
        return None

    logger.info(
        f"process_generated_images_callback: got {len(binary_images)} image(s). "
        f"Capping to {MAX_IMAGES_PER_CALL}."
    )
    # Cap number of images processed to avoid quota exhaustion
    # pyre-ignore[16]
    binary_images = binary_images[:MAX_IMAGES_PER_CALL]

    # --- 2. Combine all text into a single rich_content blob ---
    rich_content = "\n\n".join(text_chunks).strip()

    # --- 3. Determine context from session state ---
    session_id = (
        callback_context.session.id if callback_context.session else "unknown_session"
    )
    state = callback_context.state or {}
    event_id = state.get("event_id", None)
    if not event_id:
        logger.warning(
            "process_generated_images_callback: 'event_id' not found in session state. "
            f"State keys: {list(state.keys())}. Using 'unknown_event'."
        )
        event_id = "unknown_event"

    # --- 4. Infer content category from the text ---
    content_lower = rich_content.lower()
    content_category = "poster"  # default
    if "email" in content_lower or "subject:" in content_lower:
        content_category = "email"
    elif any(kw in content_lower for kw in ["instagram", "linkedin", "twitter", "social"]):
        content_category = "social_post"

    # --- 5. Upload each image and register in Firestore ---
    media_assets_info: list[dict] = []

    for idx, image_bytes in enumerate(binary_images):
        try:
            file_stem = f"gen_{uuid.uuid4().hex[:8]}"

            # Upload full-size image to GCS (offload blocking I/O to thread)
            full_uri = await asyncio.to_thread(
                resize_and_upload_image,
                image_bytes,
                dest_prefix=f"generated/{event_id}/{session_id}",
                filename=f"{file_stem}.jpg",
            )

            # Upload thumbnail to GCS
            thumb_uri = await asyncio.to_thread(
                resize_and_upload_image,
                image_bytes,
                dest_prefix=f"thumbnails/{event_id}/{session_id}",
                max_width=THUMBNAIL_MAX_WIDTH,
                filename=f"{file_stem}_thumb.jpg",
            )

            # Save the asset record in Firestore (awaited directly now)
            asset_id = await save_media_asset({
                "event_id": event_id,
                "session_id": session_id,
                "source": "agent_generated",
                "asset_type": "image",
                "subtype": None,
                "parent_asset_id": None,
                "gcs_path": full_uri,
                "public_url": gs_to_public_url(full_uri),
                "thumbnail_gcs_path": thumb_uri,
                "thumbnail_url": gs_to_public_url(thumb_uri),
                "content_category": content_category,
                "title": f"Generated Image {idx + 1}",
                "mime_type": "image/jpeg",
                "rich_content": rich_content,
                "subject": None,
            })

            media_assets_info.append({
                "asset_id": asset_id,
                "url": gs_to_public_url(full_uri),
                "thumbnail_url": gs_to_public_url(thumb_uri),
                "asset_type": "image",
                "mime_type": "image/jpeg",
            })
            logger.info(
                f"Saved agent image asset_id={asset_id} "
                f"full={full_uri} thumb={thumb_uri}"
            )
        except Exception as e:
            # Log the full traceback so we can see the real error, not just str(e)
            logger.error(
                f"Failed to process binary image {idx}: {repr(e)}\n"
                + traceback.format_exc()
            )

    # --- 6. Construct a structured JSON response for chat.py ---
    # This is the format chat.py expects to extract media_refs from
    structured_response = {
        "status": "success",
        "data": {
            "text": rich_content,
            "images": [m["url"] for m in media_assets_info],
        },
        "media_assets": media_assets_info,
        "metadata": {
            "content_category": content_category,
            "image_count": len(media_assets_info),
        },
    }

    new_text = json.dumps(structured_response, indent=2)
    logger.info(
        f"process_generated_images_callback: returning structured JSON with "
        f"{len(media_assets_info)} media_asset(s)."
    )
    return LlmResponse(
        content=genai_types.Content(
            role="model",
            parts=[genai_types.Part.from_text(text=new_text)],
        ),
        grounding_metadata=llm_response.grounding_metadata,
    )


# ---------------------------------------------------------------------------
# Agent definition
# ---------------------------------------------------------------------------

multimodal_content_creator = LlmAgent(
    name="MultimodalContentCreator",
    # Gemini model that supports interleaved text + image output.
    model="gemini-2.5-flash-image",
    description=(
        "Generates event content with interleaved text and images: "
        "invites, social posts, posters, and banners."
    ),
    # Stateless within the pipeline — reads all context from session state.
    include_contents="none",

    # CRITICAL: enable native image generation + retry on rate-limit (429)
    generate_content_config=genai_types.GenerateContentConfig(
        response_modalities=["TEXT", "IMAGE"],
        http_options=genai_types.HttpOptions(
            # Retry up to 3 times with 5-second initial backoff on 429/503
            retry_options=genai_types.HttpRetryOptions(
                initial_delay=5.0,
                attempts=3,
            ),
        ),
    ),

    instruction="""\
You are an expert event content creative director.

## Context
- Event details: {event_info?}
- Research & content plan: {research_and_plan?}
- User instructions: {user_instructions?}

## Your job
Create compelling, ready-to-publish content with text AND images.
Produce ALL requested content types in ONE single response — do not wait to be
asked again. Generate all social posts, email copy, and poster images together.

**Image limit:** Generate at most 3 images in total per response to stay within
API quotas. Prioritise the most impactful images (e.g. one hero banner, one
social graphic).

For each requested content type, write the full copy AND generate a matching
image inline. For example:
- **Email invitation** → Write the full email body (subject line, greeting,
  body, CTA) and generate a hero banner image.
- **Social media post** → Write the caption/copy and generate a matching
  graphic.
- **Poster / banner** → Generate the full poster image with all the event
  details baked into the visual design.

## Image guidelines
- Generate high-quality, visually striking images.
- Match aspect ratio to content type:
  - 16:9 for email banners or wide website heroes
  - 1:1 or 4:5 for standard social media (Instagram, Twitter)
  - 2:3 or 3:4 for promotional posters
- Use vibrant, on-brand colors and professional typography.
- Include event name, date, and venue in poster images where appropriate.

## Writing guidelines
- **Email content:** You MUST include a clear **Subject line** followed by the full **Email body**.
- **Tone:** Match the event energy: enthusiastic for parties, professional for conferences. 
- **Emoji Rules:** Use appropriate emojis for casual events. **Strictly no emojis** for official, corporate, or somber events (funerals) unless the user specifically requests them.
- **Guardrails:** Stay strictly on topic. No verbose or chatty prose.
- Use clear section headers (## or ###) to separate each content piece.
- Write polished, ready-to-use copy — not placeholder descriptions.
- Separate sections with --- markers.

If something goes wrong, explain the error clearly.
""",
    after_model_callback=process_generated_images_callback,
)
